FlatArray
anarchymonkey/frontend-developer-interview-questions pull request #2
Opened 2023-02-19 10:09 UTC by priyang12

Created FlatArray Function which is a flat function for flatting array using recursion. i have added tests to validate the function with depths.

2023-02-19 14:46 UTC, anarchymonkey requested changes
Loved the PR, added some comments. 

Thanks for contributing!

2023-02-19 14:46 UTC, anarchymonkey commented on JS/recursion/FlatArray.js
> +export const FlatArray = (InputArr, Depth = Infinity, CurrentDepth = 0) => {
method names and variable names should be `camelCase` as per industry standards

2023-02-19 14:46 UTC, anarchymonkey commented on JS/recursion/FlatArray.js
> +    const element = InputArr[i];
Pro tip: 
```
inputArr.at(i);
```

2023-02-19 14:46 UTC, anarchymonkey commented on JS/recursion/FlatArray.js
> +        const Flatten = FlatArray(element, GlobalDepth, CurrentDepth + 1);
let's change the methodName from FlatArray to `flattenArray` as method names should be verbs not nouns.

2023-02-19 17:04 UTC, priyang12 commented
@anarchymonkey hi, I have made the changes.

2023-02-20 04:40 UTC, anarchymonkey approved these changes

2023-02-20 04:40 UTC, merged